# 1. Data import & raw data information.

In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [2]:
df=pd.read_csv(r'C:\Users\alexd\Ironhack\Proyectos\Project2_DA_Ironhack\Raw - Data\w3-Database-Project-main\data\rental.csv')

df.head()

rental_id          rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30           367          130   
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   
3          4  2005-05-24 23:04:41          2452          333   
4          5  2005-05-24 23:05:21          2079          222   

           return_date  staff_id          last_update  
0  2005-05-26 22:04:30         1  2006-02-15 21:30:53  
1  2005-05-28 19:40:33         1  2006-02-15 21:30:53  
2  2005-06-01 22:12:39         1  2006-02-15 21:30:53  
3  2005-06-03 01:43:41         2  2006-02-15 21:30:53  
4  2005-06-02 04:33:21         1  2006-02-15 21:30:53

In [3]:
dim_orig=df.shape
dim_orig

(1000, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   rental_id     1000 non-null   int64 
 1   rental_date   1000 non-null   object
 2   inventory_id  1000 non-null   int64 
 3   customer_id   1000 non-null   int64 
 4   return_date   1000 non-null   object
 5   staff_id      1000 non-null   int64 
 6   last_update   1000 non-null   object
dtypes: int64(4), object(3)
memory usage: 54.8+ KB


# 2. Data Cleaning.
### Null Values

In [5]:
nan_cols=df.isnull().sum()
nan_cols[nan_cols>0]

Series([], dtype: int64)

# 3.Determination of data type per column:

**XXX** --> This would be usefull for each case identification. As we have the index for identifying each case,
let's take this column as irrelevant. That is why it is not going to be cleaned. Column type will be unchanged and it 
will remain as "Object".

**XXX** --> This must be in date time as data type. Let's going to fix it.

**XXX** --> Let's fix this column so no repeated countries are found.

In [6]:
df.rental_id.unique()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [7]:
df.customer_id.unique()

array([130, 459, 408, 333, 222, 549, 269, 239, 126, 399, 142, 261, 334,
       446, 319, 316, 575,  19, 456, 185, 388, 509, 438, 350,  37, 371,
       301, 232,  44, 430, 369, 230, 272, 597, 484,  88, 535, 302, 207,
       413, 174, 523, 532, 436,   7,  35, 282, 498,  18, 256, 507, 569,
       291, 131, 511,   6, 323, 470, 250, 419, 383, 368, 346,  86, 119,
       120, 305,  73, 100,  48, 391, 265, 510,   1, 451, 135, 245, 314,
       286, 427, 492, 414, 266, 331,  53, 499,  25, 267, 288, 197, 400,
        49, 263, 208, 468, 343, 384, 310, 108, 196, 317, 242, 503, 227,
       500,  93, 506, 455, 524,  51, 365, 405, 273,  43, 246, 439,  94,
        40,  23,  56, 325, 479, 237, 304, 504, 560, 586, 257, 354,  89,
       472, 297, 357,  82, 433, 274, 429,  14,  57, 348, 551, 462, 344,
       505, 290, 182, 296, 104, 151,  33, 322, 401, 469, 381, 107, 176,
       533, 552,  47, 548,  75, 587, 254, 556, 125, 515, 243, 247, 412,
       437, 270,  29, 564, 184, 546,  54,  71, 321, 444,  20, 10

In [8]:
df.inventory_id.unique()

array([ 367, 1525, 1711, 2452, 2079, 2792, 3995, 2346, 2580, 1824, 4443,
       1584, 2294, 2701, 3049,  389,  830, 3376, 1941, 3517,  146,  727,
       4441, 3273, 3961, 4371, 1225, 4068,  611, 3744, 4482, 3832, 1681,
       2613, 1286, 1308,  403, 2540, 4466, 2638, 1761,  380, 2578, 3098,
       1853, 3318, 2211, 1780, 2965, 1983, 1257, 4017, 1255, 2787, 1139,
       1352, 3938, 3050, 2884,  330, 4210,  261, 4008,   79, 3552, 1162,
        239, 4029, 3207, 2168, 2408, 2260,  517, 1744, 3393, 3021, 1303,
       4067, 3299, 2478, 2610, 1388,  466, 1829,  470, 2275, 1586, 2221,
       2181, 2984,  139,  775, 4360, 1675,  178, 3418, 1283, 2970,  535,
       2599,  617,  373, 3343, 4281,  794, 3627, 2833, 3289, 1044, 4108,
       3725, 2153, 2963, 4502,  749, 4453, 4278,  872, 1359,   37, 1053,
       2908, 1795,  212,  952, 2047, 2026, 4322, 4154, 3990,  815, 3367,
        399, 2272,  103, 2296, 2591, 4134,  327,  655,  811, 4407,  847,
       1689, 3905, 1431,  633, 4252, 1084,  909, 29

In [9]:
df.return_date=pd.to_datetime(df.return_date)

In [10]:
df.last_update=pd.to_datetime(df.last_update)

In [11]:
df.rental_date=pd.to_datetime(df.rental_date)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   rental_id     1000 non-null   int64         
 1   rental_date   1000 non-null   datetime64[ns]
 2   inventory_id  1000 non-null   int64         
 3   customer_id   1000 non-null   int64         
 4   return_date   1000 non-null   datetime64[ns]
 5   staff_id      1000 non-null   int64         
 6   last_update   1000 non-null   datetime64[ns]
dtypes: datetime64[ns](3), int64(4)
memory usage: 54.8 KB


In [13]:
df.head()

rental_id         rental_date  inventory_id  customer_id  \
0          1 2005-05-24 22:53:30           367          130   
1          2 2005-05-24 22:54:33          1525          459   
2          3 2005-05-24 23:03:39          1711          408   
3          4 2005-05-24 23:04:41          2452          333   
4          5 2005-05-24 23:05:21          2079          222   

          return_date  staff_id         last_update  
0 2005-05-26 22:04:30         1 2006-02-15 21:30:53  
1 2005-05-28 19:40:33         1 2006-02-15 21:30:53  
2 2005-06-01 22:12:39         1 2006-02-15 21:30:53  
3 2005-06-03 01:43:41         2 2006-02-15 21:30:53  
4 2005-06-02 04:33:21         1 2006-02-15 21:30:53

In [14]:
df.drop_duplicates().shape==df.shape # no hay duplicados

True

In [15]:
df.drop("last_update", axis=1, inplace=True)

In [ ]:
df.to_csv(r'C:\Users\alexd\Ironhack\Proyectos\Project2_DA_Ironhack\Cleaned_data\acto_cleaned.csv', index=False)